This session will cover basic consepts of linear algebra and their implemantation in numpy.

Repetition of the material from the bootcamp:

- Array creation
- Array element access
- Array addition
- Scalar multiplication


New material:

- Dot product (matrix multiplication)
- Properties of matrix multiplication
- Some useful operation in numpy

# Introduction

Vectors and matrices are one of the most fundamental building blocks of computer science. Their importance can hardly be overstated. Vectors and matrices not only make it easier to train machine learning models, they are also a great means of data representation.

## Why do we need matrices and vectors?
- Matrix (and vector) is a way to put multiple similar problems into one container or array and, then, to conduct multiple similar manipulations with it.
- Modern GPUs (Graphics Processing Units) and TPUs (Tensor Processing Units) are able to conduct efficient parallel calculations.
- There are highly optimized linear algebra libraries like numpy, pytorch, tensorflow.
- All modern neural networks (and other algorithms) are based on matrices and vectors (tensors)

## Where are you going to use them?

- Machine Learning
- Humanities Data Analysis
- Natural Language Processing
- Thesis

## Matrices and Vectors
Matrix is a rectangular (or 2-D) array of numbers:

>$A =
 \begin{pmatrix}
  10 & 19 & 40 & 20 \\
  20 & 67 & 38 & 91\\
  40  & 91  & 4 & 51  \\
  10 & 44 & 59 & 43 \\
  31 & 45 & 85 & 18
 \end{pmatrix}$

Matrices usually represent features (weights and many other things) in machine learning.

**Example:** Let's say that we would like to investigate behavior of the user Mike, who visits different websites, and find out if it is really him (fraud detection problem). In this matrix, each row corresponds to a session, and each column (except first one) corresponds to a website. The numbers may represent the amount of time spent on websites (or other features).
>|Session | Netflix| Google | Youtube| Spotify |
|:-:|:-:|:----:|:-------:|:--------:|
|0|10 | 19 | 40 | 20|
|1|20 | 67 | 38 | 91|
|2|40 | 91 | 4  |51|
|3|10 | 44 | 59 | 43|
|4|31 | 45 | 85 | 18|

Vector (1-D array) is a matrix with one column (or one row):

>$\vec{x} =
 \begin{pmatrix}
  1 \\ 19 \\ 40 \\ 20
  \end{pmatrix}$


Essentially, a vector is a list of coordinates that refers to the location of a point in space. The following vector, for instance, refers to the location of a point with $x$-coordinate 1 and $y$-coordinate 2.

> $\begin{pmatrix} 1 \\ 2\end{pmatrix}$


Dimension or shape of a matrix: $\mathbb{R}^{r \times c}$ or the number of rows $\times $ the number of columns. **QUESTION** What is dimension of  $A$ and $\vec{x}$?





# Array Creation
**IMPORTANT**: all elements of an np.array have the same type.

We can create a matrix (2-D array) or a vector (1-D array):
- from list or tuples
- filled with zeros or ones
- filled with evenly spaced values within a given interval
- reshaping another matrix or vector
- randomly
- empty


In [ ]:
import numpy as np

We can create an array using a list of lists. Each list correponds to a row in the new matrix:




In [ ]:
a_list = [[1,2,3],[4,5,6]]

In [ ]:
a_list

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a = np.array(a_list)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

Let's print out the tuple representing the dimensions of the array:  $\mathbb{R}^{r \times c}$

In [ ]:
a.shape

(2, 3)

We can also define an array using tuples:


In [ ]:
a_tuple = ((1,2,3),(4,5,6))

In [ ]:
a_tuple

((1, 2, 3), (4, 5, 6))

In [ ]:
np.array(a_tuple)

array([[1, 2, 3],
       [4, 5, 6]])

We can fill all elements with zeros or ones. Shape is defined as int or tuple of ints.

In [ ]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

We can create a vector (or 1-D array) filled with evenly spaced values within a given interval.

In [ ]:
np.arange(start=1, stop=7, step=0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

We can also create a matrix filled with evenly spaced values within a given interval. We will need the reshape method. It maps values from an existing array to an array with the given shape.

In [ ]:
np.arange(start=1, stop=7, step=0.5).reshape((4, 3))

array([[1. , 1.5, 2. ],
       [2.5, 3. , 3.5],
       [4. , 4.5, 5. ],
       [5.5, 6. , 6.5]])

Sometimes we need to create arrays filled with random ints or floats.

In [ ]:
np.random.randint(low=1, high=7, size=(5,3))

array([[1, 5, 1],
       [1, 6, 2],
       [3, 2, 5],
       [3, 1, 1],
       [2, 5, 2]])

In [ ]:
np.random.random(size=(4,4))

array([[0.46618239, 0.34779048, 0.0184451 , 0.37617211],
       [0.86081269, 0.68592824, 0.80200968, 0.14077528],
       [0.30607296, 0.47678265, 0.17703649, 0.64877259],
       [0.91083074, 0.63257037, 0.10767444, 0.03697551]])

np.random.random return floats in the half-open interval [0.0, 1.0). We can expend this interval by simple mathematical manipulations. **Question**: How to create a matrix filled with floats in the half-open interval [0.0, 100.0)? [-50.0, 50.0)?

We can also create an empty matrix. It does not contain initializing entries. (**IMPORTANT**) However, if we print it out, the matrix will contain some values. These values are already located in memory and, hence, are not random.  Empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [ ]:
np.empty(shape=(2,3))

array([[2.40626096e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

# Array element access

**IMPORTANT**: in numpy the index starts from 0.

Matrix elements or entries of matrix: $A_{i,j} = i, j$ entry in the $i^{th}$ row and $j^{th}$ column.

>$A =
 \begin{pmatrix}
  a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\
  a_{1,1} & a_{1, 1} & \cdots & a_{1,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,0} & a_{m,0} & \cdots & a_{m,n}
 \end{pmatrix}$



**QUESTION:** What is the entry of $A_{1,2}$ ?


>$A =
 \begin{pmatrix}
  10 & 19 & 40 & 20 \\
  20 & 67 & 38 & 91\\
  40  & 91  & 4 & 51  \\
  10 & 44 & 595 & 43 \\
  31 & 45 & 85 & 18
 \end{pmatrix}$


In [ ]:
b = np.arange(0,12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

We can get an element by specifying [row, column]:

In [ ]:
row = 1
column = 3
b[row, column]

7

In [ ]:
b[2, 2]

10

We can also refer to ranges inside an array. We should define *start:end:step* to specify a range:




In [ ]:
b[0, 1:3:1]

array([1, 2])

It is not necessary to assign the step. It is set to 1 by default.

In [ ]:
b[0, 1:3]

array([1, 2])

If we do not set start or end indexes, they are automatically assigned to 0 and to the last index, respectively.

In [ ]:
b[0, 1:]

array([1, 2, 3])

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0, :3]

array([0, 1, 2])

If we do not specify start, end or step we are going to refer to all indexes:


In [ ]:
b[:,  1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
b[:, ::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
b[:,-1]

array([ 3,  7, 11])

# Addition
**IMPORTANT**: Matrices must have the same shape.

Addition of two matrices is a sum of their elements one at a time.

>$ \begin{pmatrix}
  a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\
  a_{1,1} & a_{1, 1} & \cdots & a_{1,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,0} & a_{m,0} & \cdots & a_{m,n}
 \end{pmatrix} +   \begin{pmatrix}
 b_{0,0} & b_{0,1} & \cdots & b_{0,n} \\
 b_{1,1} & b_{1, 1} & \cdots & b_{1,n} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
 b_{m,0} & b_{m,0} & \cdots & b_{m,n}
 \end{pmatrix} =
  \begin{pmatrix}
  a_{0,0} + b_{0,0} & a_{0,1} + b_{0,1} & \cdots & a_{0,n} + b_{0,n} \\
 a_{1,1} + b_{1,1} & a_{1, 1} + b_{1, 1} & \cdots & a_{1,n} + b_{1,n} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
 a_{m,0} + b_{m,0} & a_{m,0} + b_{m,0} & \cdots & a_{m,n}  + b_{m,n}
  \end{pmatrix} $

**EXAMPLE:**
>$
 \begin{pmatrix}
  1 & 19 & 40 & 20 \\
  2 & 67 & 38 & 91\\
  4  & 91  & 4 & 51
 \end{pmatrix} + \begin{pmatrix}
  10 & 1 & 4 & 5 \\
  12 & 6 & 8 & 1\\
  14  & 3 & 7 & 6
 \end{pmatrix} = \begin{pmatrix}
  1 + 10  & 19 + 1 & 40 + 4 & 20 + 5 \\
  2 + 12 & 67 + 6 & 38 + 8 & 91 + 1 \\
  4 + 14  & 91 + 3  & 4 +7 & 51  + 6
 \end{pmatrix} = \begin{pmatrix}
  11  & 20 & 44 & 25 \\
  14 & 73 & 46 & 92 \\
  18  & 94  & 11 & 57
 \end{pmatrix} $

In [ ]:
a = np.arange(0,12).reshape((3,4))
b = np.arange(12,24).reshape((3,4))

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a - b

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

As it was mentioned, matrices must have the same shape to get added up. Hence, we can not sum up matrices of different shapes (and vectors).

**IMPORTANT:** However, numpy allows some of fobidden operations in linear algebra. It is done for convinience.  **EXAMPLE**: Let's say that we have a feature matrix for the user Mike who visits different websites. Here, each number corresponds to the time when Mike starts to visit a website (it is time in hours):
>|Session | Netflix| Google | Youtube| Spotify |
|:-:|:-:|:----:|:-------:|:--------:|
|0 | 10 | 19 | 4 | 2 |
|1 | 12 | 6 | 3 | 9 |
|2 | 4  | 9  | 4 | 15  |
|3 | 1 | 14 | 5 | 3 |
|4 | 3 | 5 | 8 | 11 |

However, the websites are located in different timezones and we would like to change this time to the local time of Mike. It means that we should add to each column a number corresponding to the time shift.

>|Session | Netflix| Google | Youtube| Spotify |
|:-:|:-:|:----:|:-------:|:--------:|
|0 | 10 + 1 | 19 + 2| 4 + 3 | 2 + 4|
|1 | 12 + 1 | 6 + 2 | 3 + 3 | 9 + 4 |
|2 | 4 + 1 | 9 + 2  | 4 + 3 | 15 + 4 |
|3 | 1 + 1| 14 + 2 | 5 + 3 | 3 + 4 |
|4 | 3 + 1| 5 + 2| 8 + 3 | 11 + 4 |


For such cases, numpy allows us to add up a matrix and a row vector if they have the same amount of columns.

In [ ]:
a = np.arange(0,12).reshape((3,4))
b = np.arange(12,24).reshape((3,4))

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[[0]]

array([[0, 1, 2, 3]])

In [ ]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
 b.shape

(3, 4)

In [ ]:
a[[0]].shape

(1, 4)

In [ ]:
a[[0]] + b

array([[12, 14, 16, 18],
       [16, 18, 20, 22],
       [20, 22, 24, 26]])

We can also add up a matrix and a column vector if they have the same amount of rows.

In [ ]:
a[:,[0]]

array([[0],
       [4],
       [8]])

In [ ]:
a[:,[0]] + b

array([[12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

# Scalar Multiplication
Scalar (it is just a number) multiplication is multiplication of a matrix and a number:

>$ n \times \begin{pmatrix}
  a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\
  a_{1,1} & a_{1, 1} & \cdots & a_{1,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,0} & a_{m,0} & \cdots & a_{m,n}
 \end{pmatrix} =   \begin{pmatrix}  
 n \times a_{0,0} & n \times a_{0,1} & \cdots & n \times a_{0,n} \\
 n \times a_{1,1} & n \times a_{1, 1} & \cdots & n \times a_{1,n} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
 n \times a_{m,0} & n \times a_{m,0} & \cdots & n \times a_{m,n}
  \end{pmatrix} $

**EXAMPLE**:

>$ 2 \times
 \begin{pmatrix}
  10 & 1 & 4 & 5 \\
  12 & 6 & 8 & 1\\
  14  & 3 & 7 & 6
 \end{pmatrix} = \begin{pmatrix}
  2 \times 10 & 2 \times 1 & 2 \times 4 & 2 \times 5 \\
  2 \times 12 & 2 \times 6 & 2 \times 8 & 2 \times 1\\
  2 \times 14  & 2 \times 3 & 2 \times 7 & 2 \times 6
 \end{pmatrix} = \begin{pmatrix}
  20  & 2 & 8 & 10 \\
  24 & 12 & 16 & 2 \\
  28  & 6  & 14 & 12
 \end{pmatrix} $

In [ ]:
a = np.arange(0,12).reshape((3,4))

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

**IMPORTANT:** Similarly to matrix addition, numpy allows us to conduct element-wise (scalar) multiplication of two matrices.

In [ ]:
a = np.arange(0,12).reshape((3,4))
b = np.arange(12, 24).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a/b

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

We can also conduct element-wise (scalar) multiplication of a matrix and a row vector if they have the same amount of columns. It also works for column vectors.

In [ ]:
b = np.array([[1, 0, 2, 4]])

In [ ]:
b.shape

(1, 4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b*a

array([[ 0,  0,  4, 12],
       [ 4,  0, 12, 28],
       [ 8,  0, 20, 44]])

In [ ]:
b = np.array([[1], [0], [3]])

In [ ]:
b.shape

(3, 1)

In [ ]:
a*b

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [24, 27, 30, 33]])

# Dot Product (or Matrix Multiplication) of Two Vectors
**IMPORTANT**: Vectors must have the same size (or dimension).

**IMPORTANT**: We can only multiply a row vector by a column vector.

$\begin{pmatrix}
  a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\
 \end{pmatrix} \times \begin{pmatrix}
  b_{0,0}  \\
  b_{1,0}  \\
  \vdots    \\
  b_{n,0}
 \end{pmatrix} = \sum_{i=0}^n \ a_{0,i} \times b_{i,0}$

**EXAMPLE**:
>$\begin{pmatrix}
  1 & 2 & 3 & 4 \\
 \end{pmatrix} \times
 \begin{pmatrix}
  5 \\ 6 \\ 7 \\8
  \end{pmatrix} =  \begin{pmatrix}
  1 \times 5  + 2 \times 6 +  3 \times 7 +  4 \times 8 \\
 \end{pmatrix} =  \begin{pmatrix}
  5  + 12 +  21 +  32 \\
 \end{pmatrix} = 70 $

**EXAMPLE**: Let's say that we have a real estate agency that rents out apartments and we would like to rent out an unfurnished apartment with a size of 50 $m^2$, located in the city center, with a garden :
>$Price(size, center[0 \, or \,1], furniture[0 \, or \,1]], garden[0 \, or \,1])= 10 \times size + 50 \times center + 25 \times furniture + 40 \times garden = \begin{pmatrix}
  size &  center[yes?] & furniture[yes?] & garden[yes?] \\
 \end{pmatrix} \times
 \begin{pmatrix}
  10 \\ 50 \\ 25 \\40
  \end{pmatrix} $


>$\begin{pmatrix}
  50 & 1 & 0 & 1 \\
 \end{pmatrix} \times
 \begin{pmatrix}
  10 \\ 50 \\ 25 \\40
  \end{pmatrix} =  \begin{pmatrix}
  50 \times 10 + 1 \times  50 + 0 \times 25 + 1 \times  40\\
 \end{pmatrix} = 590 $




In [ ]:
a = np.array([[50, 1, 0 , 1]])
b = np.array([[10], [50], [25], [40]])

In [ ]:
a.shape

(1, 4)

In [ ]:
b.shape

(4, 1)

In [ ]:
np.dot(a, b)

array([[590]])

However, numpy allows us to avoid rotation of the first vector:

In [ ]:
a = np.array([50, 1, 0 , 1])
b = np.array([10, 50, 25, 40])

In [ ]:
a

array([50,  1,  0,  1])

In [ ]:
a.shape

(4,)

In [ ]:
np.dot(a, b)

590

# Dot Product (or Matrix Multiplication) of Matrix and Vector

Let's say that we have two apartments to rent out :

>$\begin{pmatrix}
  50 & 1 & 0 & 1 \\
  100 & 1 & 1 & 1
 \end{pmatrix} \times
 \begin{pmatrix}
  10 \\ 50 \\ 25 \\40
  \end{pmatrix} =  \begin{pmatrix}
  50 \times 10 + 1 \times  50 + 0 \times 25 + 1 \times  40\\
  100 \times 10 + 1 \times  50 + 1 \times 25 + 1 \times  40
 \end{pmatrix} = \begin{pmatrix}590 \\ 1115 \end{pmatrix} $




In [ ]:
a = np.array([[50, 1, 0 , 1], [100, 1, 1 , 1]])
b = np.array([[10], [50], [25], [40]])

In [ ]:
a.shape

(2, 4)

In [ ]:
b.shape

(4, 1)

In [ ]:
np.dot(a, b)

array([[ 590],
       [1115]])

# Matrix-Matrix Multiplication (Dot Product)
Let's say that we have two real estate agencies:

>$\begin{pmatrix}
  50 & 1 & 0 & 1 \\
  100 & 1 & 1 & 1
 \end{pmatrix} \times
 \begin{pmatrix}
  10 & 11 \\ 50 & 20 \\ 25 & 30 \\40 & 35
  \end{pmatrix} =  \begin{pmatrix}
  50 \times 10 + 1 \times  50 + 0 \times 25 + 1 \times  40 & 50 \times 11 + 1 \times  20 + 0 \times 30 + 1 \times  35\\
  100 \times 10 + 1 \times  50 + 1 \times 25 + 1 \times  40 & 100 \times 11 + 1 \times  20 + 1 \times 30 + 1 \times 35
 \end{pmatrix} = \begin{pmatrix} 590 & 605  \\ 1115 & 1185 \end{pmatrix} $

**General rule**:
>$ \begin{pmatrix}
  a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\
  a_{1,1} & a_{1, 1} & \cdots & a_{1,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,0} & a_{m,0} & \cdots & a_{m,n}
 \end{pmatrix} \times   \begin{pmatrix}
 b_{0,0} & b_{0,1} & \cdots & b_{0,k} \\
 b_{1,1} & b_{1, 1} & \cdots & b_{1,k} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
 b_{n,0} & b_{n,0} & \cdots & b_{n,k}
 \end{pmatrix} = \begin{pmatrix}
   \sum_{i=0}^n \ a_{0,i} \times b_{i,0} & \sum_{i=0}^n \ a_{0,i} \times b_{i,1} & \cdots & \sum_{i=0}^n \ a_{0,i} \times b_{i,k} \\
 \sum_{i=0}^n \ a_{1,i} \times b_{i,0} & \sum_{i=0}^n \ a_{1,i} \times b_{i,1} & \cdots & \sum_{i=0}^n \ a_{1,i} \times b_{i,k} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
  \sum_{i=0}^n \ a_{m,i} \times b_{i,0} & \sum_{i=0}^n \ a_{m,i} \times b_{i,1} & \cdots & \sum_{i=0}^n \ a_{m,i} \times b_{i,k}
  \end{pmatrix}$

**IMPORTANT**: The first matrix must have a number of columns to a number of rows in the second matrix.

Shape(A) = (m , n)

Shape(B) = (n , k)

Shape(AB) = (m, k)




In [ ]:
a = np.array([[50, 1, 0 , 1], [100, 1, 1 , 1]])
b = np.array([[10 , 11], [50, 20], [25, 30], [40, 35]])

In [ ]:
a.shape

(2, 4)

In [ ]:
b.shape

(4, 2)

In [ ]:
b

array([[10, 11],
       [50, 20],
       [25, 30],
       [40, 35]])

In [ ]:
b.T

array([[10, 50, 25, 40],
       [11, 20, 30, 35]])

In [ ]:
# check it!
# np.dot(a, b.T)

In [ ]:
np.dot(a, b)

array([[ 590,  605],
       [1115, 1185]])

# Properties of Matrix Multiplication (Check at home)

- Matrix multiplication is not commutative:
$A\times B \neq B \times A$
- Matrix multiplication is assosiative: $(A\times B) \times C = A\times (B \times C)$
- Identity Matrix ($n \times n $ matrix with diagonal elements consisting of ones): $I\times B = B$
- Inverse Matrix ($n \times n $ matrix): $B\times B^{-1} = I$




In [ ]:
a = np.arange(0, 9).reshape((3, 3))
b = np.arange(9, 18).reshape((3, 3))
c = np.arange(18, 27).reshape((3, 3))

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
c

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

Matrix multiplication is not commutative:
$A\times B \neq B \times A$:

In [ ]:
np.dot(a, b)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [ ]:
np.dot(b, a)

array([[ 96, 126, 156],
       [123, 162, 201],
       [150, 198, 246]])

Matrix multiplication is assosiative:
$(A\times B) \times C = A\times (B \times C)$


In [ ]:
ab = np.dot(a, b)
bc = np.dot(b, c)

In [ ]:
np.dot(ab, c)

array([[ 2853,  2988,  3123],
       [10278, 10764, 11250],
       [17703, 18540, 19377]])

In [ ]:
np.dot(a, bc)

array([[ 2853,  2988,  3123],
       [10278, 10764, 11250],
       [17703, 18540, 19377]])

Identity Matrix ($n \times n $ matrix with diagonal elements consisting of ones): $I\times B = B$

In [ ]:
 np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.dot(np.identity(3), a)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Inverse Matrix ($n \times n $ matrix): $B\times B^{-1} = I$

In [ ]:
6*(1/6)

1.0

In [ ]:
a_random = np.random.random(size=(4,4))
a_random

array([[0.58908373, 0.05185454, 0.77489686, 0.21860354],
       [0.36489372, 0.80311914, 0.14377386, 0.5981189 ],
       [0.57397031, 0.63659944, 0.23177893, 0.66495112],
       [0.81093856, 0.01251471, 0.12470146, 0.66033814]])

In [ ]:
a_random_inv = np.linalg.inv(a_random)
a_random_inv

array([[ -10.88124501,  -75.94893702,   97.20279943,  -25.48684679],
       [  -5.33147513,  -35.57515781,   47.15116512,  -13.49243049],
       [   6.4654702 ,   35.50694528,  -45.54874653,   11.56519643],
       [  12.24295395,   87.23919302, -111.66337615,   30.88557598]])

In [ ]:
np.dot(a_random, a_random_inv)

array([[ 1.00000000e+00, -5.00796691e-16,  3.56222243e-15,
         8.08995243e-17],
       [-1.30648695e-15,  1.00000000e+00,  1.07490879e-14,
        -2.53678716e-15],
       [ 7.30202905e-16,  7.52533117e-15,  1.00000000e+00,
         3.37279868e-15],
       [-5.56951801e-16, -2.13941287e-15,  3.78986319e-16,
         1.00000000e+00]])

In [ ]:
np.around(np.dot(a_random, a_random_inv)).astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Useful operations (Check at home)

In [ ]:
a = np.arange(0, 9).reshape((3, 3))
b = np.arange(9, 18).reshape((3, 3))

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

Sum of all elements in a matrix:

In [ ]:
np.sum(a)

36

Sum of all elements in each column



In [ ]:
np.sum(a, axis=0)

array([ 9, 12, 15])

Sum of all elements in each row:


In [ ]:
np.sum(a, axis=1)

array([ 3, 12, 21])

We can concatenate 2 matrices (or tables) with the same features (columns):

In [ ]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

We can also concatenate 2 matrices (or tables) with the same number of observations (rows):

In [ ]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

The transpose of a matrix is an operator which flips a matrix over its diagonal  (rotation on 90 degrees). It is usually denoted by $A^T$ for a matrix $A$.

In [ ]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
b.T

array([[ 9, 12, 15],
       [10, 13, 16],
       [11, 14, 17]])

In [ ]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

# Exercises

*  Matrix A[3x3]; Matrix B[3x3]
*  create both matrices in numpy
*  vector c [3]; vector d [3]
*  create vector c in numpy
*  work out A + B
*  work out 2 * A
*  work out c * A
*  work out the dot product of c and d
*  work out A*B (by hand and in numpy; compare the results)
*  work out B*A (by hand and in numpy; compare the results)
*  Is $A \times B $ equal to $ B \times A$? Why (not)?
*  Is $(A\times B) \times C$  equal to $A\times (B \times C)$ Why (not)?




